In [8]:
# 讀取numpy函式庫
import numpy as np
# 用np內的random取代python的random
import numpy.random as random
# 讀取scipy函式庫
import scipy as sp
# 讀取pandas函式庫
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
# 讀取matplotlib函式庫
import matplotlib as mpl
# 讀取seaborn函式庫
import seaborn as sns
%matplotlib inline

# 意指
%precision 3

'%.3f'

In [9]:
# 製作陣列
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [11]:
# 資料的型別
print('資料類型:', data.dtype)
# 陣列的維度
print('陣列維度:', data.ndim)
# 元素的數量
print('元素數量:', data.size)

資料類型: int32
陣列維度: 1
元素數量: 10


In [ ]:
# 將各個數字乘上數倍
print(data * 2)
# 將各對應的數字進行運算
print('乘法運算:', np.array([1, 2, 3, 4, 5]) * np.array([5, 4 , 3, 2, 1]))
print('連乘:', np.array([1, 2, 3, 4, 5]) ** 2)
print('除法運算:', np.array([1, 2, 3, 4, 5]) / np.array([5, 4, 3, 2, 1]))

In [12]:
# 排序
# 顯示目前的值
print('原本的值:', data)
# 顯示排序後的值(由小到大)
data.sort()
print('由小到大排序:', data)
# 顯示排序後的值(由大到小)
data[::-1].sort()
print('由大到小排序:', data)


原本的值: [ 9  2  3  4 10  6  7  8  1  5]
由小到大排序: [ 1  2  3  4  5  6  7  8  9 10]
由大到小排序: [10  9  8  7  6  5  4  3  2  1]


In [13]:
# 最小值
print('最小值(Min):', data.min())
# 最大值
print('最大值(Max):', data.max())
# 總和
print('總和(Sum):', data.sum())
# 累積和
print('累積和(Cum):', data.cumsum())
# 累積比例 = 累積和 / 總和
print('累積比例(Ratio):', data.cumsum() / data.sum())

最小值(Min): 1
最大值(Max): 10
總和(Sum): 55
累積和(Cum): [10 19 27 34 40 45 49 52 54 55]
累積比例(Ratio): [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [15]:
# 亂數
# 亂數種子:可以固定取得的亂數，裡面填的數字為代號，後續用相同的種子，會有相同的亂數值
random.seed(0)
# random.randn()常態分佈(平均為0,標準差為1)亂數
rnd_data = random.randn(5)
print('含有5個亂數的陣列:', rnd_data)
# random.rand():均勻分布。0.0以上、小於1.0
# random.random_sample():均勻分布。0.0以上、小於1.0(和rand的引數指定方法不同)
# random.randint():均勻分布。任意範圍的整數
# random.randn():常態分布。平均為0、標準差為1的整數
# random.normal():常態分布。任意平均、標準差的亂數
# random.binomial():二項分布的亂數
# random.beta():貝他分布的亂數
# random.gamma():伽瑪分布的亂數
# random.chisquare():卡方分布的亂數


含有5個亂數的陣列: [1.764 0.4   0.979 2.241 1.868]


In [16]:
# 資料的隨機取出
data = np.array([9,2,3,4,10,6,7,8,1,5])

# 隨機取出10個(允許重複，放回抽樣)
print(random.choice(data, 10))
# 隨機取出10個(不允許重複，不放回抽樣)
print(random.choice(data, 10, replace = False))


[10  8  7  1  1  2  7  8  8  1]
[ 3 10  4  7  8  9  1  5  6  2]


In [17]:
# 比較有無使用numpy的速度
# %timeit():檢查運算時間
N = 10**6

normal_data = [random.random() for _ in range(N)]
numpy_random_data = np.array(normal_data)
# 取總和:一般的處理
%timeit sum(normal_data)
# 取總和:numpy的處理
%timeit np.sum(numpy_random_data)


3.28 ms ± 48.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
364 µs ± 20.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
# 建立內容0-8的一維矩陣:np.arange()
print(np.arange(9))
print('\n')
# 建立內容0-8的3*3的矩陣np.reshape()
array1 = np.arange(9).reshape(3,3)
print(array1)
print('\n')
# 顯示row0
print(array1[0,:])
print('\n')
# 顯示column0
print(array1[:,0])
print('\n')

# 建立內容9-17的3*3的矩陣
array2 = np.arange(9,18).reshape(3,3)
print(array2)
print('\n')
# 矩陣的積
print(np.dot(array1,array2))
print('\n')
# 元素各自的積
print(array1 * array2)

[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[0 1 2]


[0 3 6]


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [21]:
# 元素0或1的矩陣:np.zeros(), np.ones()
print(np.zeros((2,3), dtype = np.int64))
print('\n')
print(np.ones((2,3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]


[[1. 1. 1.]
 [1. 1. 1.]]


練習一
計算1到50的自然數總和，並顯示最後的計算結果的程式。(使用np.array來製作1到50的陣列，再來求得總和)

In [20]:
numpy_sample_data = np.array([i for i in range(1,51)])
print((numpy_sample_data))
print('總和為:', numpy_sample_data.sum())


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
1275


練習二
依據常態分布生成10個亂數並製作陣列，求其最小值、最大值、總和的程式

In [22]:
random.seed(0)
norm_random_sample_data = random.randn(10)

print("最小値：",norm_random_sample_data.min())
print("最大値：",norm_random_sample_data.max())
print("合計：",norm_random_sample_data.sum())


最小値： -0.977277879876411
最大値： 2.240893199201458
合計： 7.380231707288347


練習三
製作所有元素均為3的5*5陣列，並計算該矩陣的平方

In [23]:
m =  np.ones((5,5),dtype='i') * 3
print(np.dot(m, m))


[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
