In [1]:
# 讀取numpy函式庫
import numpy as np
# 用np內的random取代python的random
import numpy.random as random

# 讀取scipy函式庫
import scipy as sp
# 用於線性代數的函式庫
import scipy.linalg as linalg
# 用於最佳化計算(最小值)的函式
from scipy.optimize import minimize_scalar

# 讀取pandas函式庫
import pandas as pd
# 處理1維陣列的Series函式庫與處理2維陣列的DataFrame函式庫
from pandas import Series, DataFrame

# 讓pyplot能以別名plt來執行，多數的描繪功能都在pyplot內
import matplotlib.pyplot as plt
# 讀取matplotlib函式庫
import matplotlib as mpl
# seaborn函式庫能讓圖表更美觀
import seaborn as sns
# 在jupyter notebook上顯示圖表所必須的magic command
%matplotlib inline

# 意指顯示到小數點後第三位
%precision 3

'%.3f'

In [2]:
matrix = np.array([[1,-1,-1], [-1,1,-1], [-1,-1,1]])

# 行列式
print('行列式')
print(linalg.det(matrix))
print('\n')
# 反矩陣
print('反矩陣')
print(linalg.inv(matrix))
print('\n')
# 驗證:原始矩陣與反矩陣的乘積會為單位矩陣
print(matrix.dot(linalg.inv(matrix)))
print('\n')

# 特徵值與特徵向量:linalg.eig()
eig_value, eig_vector = linalg.eig(matrix)
print('特徵值')
print(eig_value)
print('\n')
print('特徵向量')
print(eig_vector)

行列式
-4.0


反矩陣
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


特徵值
[-1.+0.j  2.+0.j  2.+0.j]


特徵向量
[[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


In [3]:
# 牛頓法
# 方程式求解
# 函數的定義
def my_function(x):
    return (x**2 + 2*x + 1)

# 匯入牛頓法
from scipy.optimize import newton
# 執行計算。求f(x)=0的x
print(newton(my_function,0))

# 求最小值:brent法
print(minimize_scalar(my_function, method = 'Brent'))


-0.9999999852953906
     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002


練習一                     [1 2 3]
請對下面的矩陣計算行列式    A= [1 3 2]
                          [3 1 2]

In [4]:
import scipy.linalg as linalg

a = np.array([[1,2,3],[1,3,2],[3,1,2]])
print('行列式結果:', linalg.det(a))


行列式結果: -12.0


練習二
對練習一的矩陣，計算反矩陣、特徵值和特徵向量

In [5]:
print('反矩陣結果:'+'\n', linalg.inv(a))
eig_value, eig_vector = linalg.eig(a)
print('特徵值:'+'\n', eig_value)
print('特徵向量:'+'\n', eig_vector)


反矩陣結果:
 [[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
特徵值:
 [ 6.   +0.j -1.414+0.j  1.414+0.j]
特徵向量:
 [[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]


練習三
使用牛頓法，求得能讓下面函數為0的解
f(x)=x^3+2x+1

In [6]:
from scipy.optimize import newton
def sample_function1(x):
    return (x**3 + 2*x + 1)
print(newton(sample_function1,0))
# 驗證
print(sample_function1(newton(sample_function1,0)))


-0.45339765151640365
3.3306690738754696e-16
